import localFont from "next/font/local";
// 구글폰트에서 폰트 import하기
import {Jaro} from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const jaro = Jaro({subsets: ["latin"], weight: "700"})
/*
import {Jaro} from "next/font/google";
Jaro라는 이름은 폰트 자체 고유이름이기 때문에, 변경이 불가능하고 대소문자를 구별해야 한다.
*구글폰트에 있어도 nextfont에는 없는 경우가 있다.(에러가 출력됨)

const jaro를 사용하여 Jaro로 불러온 폰트를 설정
subsets: 웹 폰트에서 특정 문자만 불러오도록 지정(로딩시간을 줄이기 위함)
한글: korean
영어권: latin
*/

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}


/*
nextJs에서 폰트 적용하는 방법

구글폰트를 이용하는 방법
*/